### ISSUE TITLE
How to test auth decorated functions ?

### ISSUE THREAD

**Issue by ramstein74** [viniciusban/web2py.test#10]
Hello i need help on how  to test a controller function decorated with auth.requires

i have 

@auth.requires(True, requires_login=  request.is_local)
def execdal():
	return dict(ret=1)

my pytest function
def test_execdal(web2py):
    result = web2py.run('default', 'execdal', web2py)

i get an error about redirected because i think it forces to loggin 
![image](https://user-images.githubusercontent.com/1210858/29498964-87f23f38-85fe-11e7-8f52-7c122491d69a.png)

Can you help?

**Comment by viniciusban** [comment]
Sorry, I don't work with web2py for a long time.
